# Generated by Django 3.2.8 on 2023-01-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20230123_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='今日の記録',
            name='department',
        ),
        migrations.DeleteModel(
            name='クラス',
        ),
        migrations.DeleteModel(
            name='今日の記録',
        ),
    ]
