# Generated by Django 3.2.8 on 2023-01-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_class_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='name',
            new_name='person',
        ),
    ]
