# Generated by Django 3.2.8 on 2023-01-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_rename_name_record_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='teacher',
            field=models.TextField(default=2, verbose_name='先生から:'),
            preserve_default=False,
        ),
    ]
